### ISSUE TITLE
Grammatical error in the word

### ISSUE THREAD

**Issue by Ai-Vonie** [caiyucong/sky-auto-player#1]
![Снимок экрана 2024-11-19 134407](https://github.com/user-attachments/assets/fe7d921a-e302-4801-8d31-74acbcb01ca3)
![Снимок экрана 2024-11-19 134432](https://github.com/user-attachments/assets/f235142b-9930-43b3-8396-cf635898330c)
Change to sky-auto-pa**l**yer -> sky-auto-p**l**ayer

**Comment by yuki-sakura-chan** [comment]
thx
