### ISSUE TITLE
Error unloading processes after trying to close the application

### ISSUE THREAD

**Issue by Ai-Vonie** [caiyucong/sky-auto-player#4]
Steps to reproduce the error:
1) Launch GUI
2) Start playing the song in demo mode
3) Close the application window
The song will continue to play along with logging, and the process will not be released from the Windows task manager.
[Comparing changes](https://github.com/yuki-sakura-chan/sky-auto-player/compare/master...Ai-Vonie:SkyAutoPlayer_Test:master)

This problem is solved by either this code:
```
        current_pid = os.getpid()
        os.kill(current_pid, signal.SIGTERM)
```

Can try to stop processes by implementing conditions for checking `stop_end` and releasing resources, but I couldn't implement it correctly. If you want a pull request, you will need to clean up `stop_end` of the new code.

**Comment by yuki-sakura-chan** [comment]
Hello, I couldn’t reproduce the issue based on your steps. Could you please provide more details? For example, your system and development environment.

**Comment by Ai-Vonie** [comment]
1. Launch `gui.py`
2. Go to `Player`
3. Select a song
4. Start playing the song in demo mode
5. Wait until the song loads and start playing sound using demo mode.
6. Close the application window using `closeEvent`
7. Due to an unclosed process in the Windows task manager, the song continues to play and logs are also recorded.

![Screenshot_1](https://github.com/user-attachments/assets/6ef32907-b4a0-4e54-bcaf-2b725f8f301d)
![Screenshot_2](https://github.com/user-attachments/assets/240b0f74-a51b-4c95-a17c-c7fc3089b8c0)
![Screenshot_3](https://github.com/user-attachments/assets/a62e26ff-4b69-4a60-8f49-e24c6dd3e496)
![Screenshot_4](https://github.com/user-attachments/assets/f144f4a6-84ce-450b-8a0d-fb0ab2ed7bd7)
![Screenshot_5](https://github.com/user-attachments/assets/6c4f4649-19d5-4703-b30d-61a85e688cd6)
![Screenshot_7](https://github.com/user-attachments/assets/0f03b77c-5335-4853-b4bb-0d617bc041ae)



Windows 11 Pro 10.0.22621

Python 3.10.11

adafruit-board-toolkit==1.1.1
annotated-types==0.7.0
astroid==2.15.8
asttokens==2.2.1
bcrypt==3.2.2
bitarray==2.8.3
bitstring==4.1.2
certifi==2024.8.30
cffi==1.16.0
chardet==5.2.0
charset-normalizer==3.4.0
colorama==0.4.6
colorthief==0.2.1
cryptography==38.0.4
darkdetect==0.8.0
dill==0.3.7
docutils==0.20.1
ecdsa==0.18.0
esptool==4.6.2
idna==3.10
isort==5.12.0
jedi==0.18.2
keyboard==0.13.5
lazy-object-proxy==1.9.0
mccabe==0.7.0
mypy==1.5.1
mypy-extensions==1.0.0
numpy==2.1.3
paramiko==3.2.0
parso==0.8.3
pillow==10.4.0
platformdirs==4.0.0
pycparser==2.21
pydantic==2.9.2
pydantic_core==2.23.4
PyDirectInput==1.0.4
pygame==2.6.1
pylint==2.17.7
PyNaCl==1.5.0
pynput==1.7.7
pyserial==3.5
PySide6==6.7.3
PySide6-Fluent-Widgets==1.6.6
PySide6_Addons==6.7.3
PySide6_Essentials==6.7.3
PySideSix-Frameless-Window==0.4.3
pywin32==308
PyYAML==6.0.1
reedsolo==1.7.0
requests==2.32.3
scipy==1.14.1
Send2Trash==1.8.2
shiboken6==6.7.3
six==1.16.0
thonny==4.1.4
tomli==2.0.1
tomlkit==0.12.3
typing_extensions==4.8.0
urllib3==2.2.3
websockets==11.0.3
wrapt==1.16.0

**Comment by Ai-Vonie** [comment]
After closing the application window, if you try to delete the file with the logs when the process in the task manager is running, you will not be able to, since this file is occupied by the Python processor.

**Comment by yuki-sakura-chan** [comment]
Hello, I used a Hyper-V virtual machine to simulate a Windows 11 system and matched the Python and Pygame versions you’re using. However, I still couldn’t reproduce the issue. It might require you to troubleshoot it further on your end.

**Comment by Ai-Vonie** [comment]
The problem has been resolved.
