### ISSUE TITLE
RAM leak

### ISSUE THREAD

**Issue by Ai-Vonie** [caiyucong/sky-auto-player#8]
@yuki-sakura-chan . When a new song is launched, the RAM increases by 10 megabytes. And so with each new music. This problem has grown in my [new pull request](https://github.com/yuki-sakura-chan/sky-auto-player/pull/9) to the fact that with each new slider movement, the RAM increases by 10 megabytes.

**Comment by yuki-sakura-chan** [comment]
@Ai-Vonie
Since I store the file list in memory after loading, I plan to optimize it after updating the cloud music library.


Recently, the game I’ve been playing released a new version, and my focus has been on the game. I’ll start coding once I have some free time.

**Comment by Ai-Vonie** [comment]
@yuki-sakura-chan , I fixed the RAM leak in the [new commit](https://github.com/yuki-sakura-chan/sky-auto-player/pull/9/commits/e997dd2e736239d28e18456cbc60747b35e7671b). You didn't clear the audio channels for the songs.
